### ISSUE TITLE
Date UDFs - day and month values swapping around

### ISSUE THREAD

**Issue by am-esdm** [exeGesIS-SDM/CAMS-Mobile#56]
In CAMS Mobile v4.3.9, when you create a new record (doesn't matter which type) or update an existing record and include a value for a date-format UDF field (e.g. 1st June 2019 i.e. 01/06/2019), then save the record, then re-open the record the day and month values in the record will have switched around (i.e. the example value above will now show as 6th January 2019, i.e. 06/01/2019), then if the user saves that record of course the wrong date value is saved

**Comment by LaineS** [comment]
Fixed in v4.3.10, the day and month values should be correct now

**Comment by am-esdm** [comment]
This one needs a bit more work as whilst the initial visible issue described above appears to be resolved (from testing only on the older Samsung Galaxy Tab A device so far, not the Active 2 device yet), a knock-on problem still exists, in that CAMS Desktop and (as far as I understand it, probably:) CAMS Web in their current versions require a UDF date value in the format of DD MMM YYYY (i.e. with spaces in between and a 3-letter text month format e.g. 26 Mar 2019, as opposed to 26/03/2019, 26-03-2019, 03/26/2019 or any other arrangement).

The result of this problem is that the current date UDF values from the central SQL Server CAMS database are showing as NaN/NaN/0NaN on Mobile, presumably as Mobile isn't expecting the same date format - I thought this same problem was initially resolved in CAMS Mobile v4.3.9, but of course that version had the problem with the date and month values swapping around as described above. 

- So if you enter a new UDF date value in CAMS Mobile, this displays in Mobile ok, but syncs back to the database in the format 05/09/2019, which CAMS Desktop can actually handle and displays as 05 Sep 2019 but this isn't the desired format, or consistent with the other values' format in the database, and I believe may have accessibility standards problems for CAMS Web

- Furthermore, if you enter any new records in Desktop with a date UDF value, or have existing records from the database with a date UDF value, after syncing back to Mobile these will display as NaN/NaN/0NaN. If you then edit one of these records with this NaN/NaN/0NaN value, e.g. edit a different field so that the record needs to be synced back, then sync it back to Desktop and import the update, the existing UDF date value gets wiped and replaced with a database value of '01/01/1901', displaying in CAMS Desktop as '01 Jan 1901'

LS: Please can you therefore apply the following format to the date UDFs in CAMS Mobile: DD MMM YYYY (i.e. with spaces in between and a 3-letter text month format e.g. 26 Mar 2019). Thanks

**Comment by LaineS** [comment]
This is a new issue and not related to the main one here. So I'll create a new GitHub issue for it.

**Comment by am-esdm** [comment]
Now tested the original version of this issue in v4.3.11 using the Samsung Galaxy Tab Active 2 device (on Android v8.1), seems to be working fine on that device. Need to test on the older Samsung Galaxy Tab A device and pass to the wider CAMS Team for more varied testing before this can be signed off. Will respond separately to the newer knock-on Issue regarding date UDF value formats

**Comment by LaineS** [comment]
More testing needed

**Comment by am-esdm** [comment]
I completed more detailed testing on this a while back and it was all fine, but the CAMS Web interaction element is still untested and this is an outstanding task that was assigned to RC/DB a while back, I've just emailed RC again to remind him, then if the CAMS Web interaction is all fine we will be able to close this issue
